### PR TITLE
Added reproducible for rskj/hop-4.1.0

### PR DESCRIPTION
**Pull request by Vovchyk**
```shell
$ docker run --rm rskj/4.1.0-hop sh -c 'sha256sum * | grep -v javadoc.jar'
d5ec4c766b184d13dde8c4cdef6f30481731b72c562c087bfd0c223d5709a2e6  rskj-core-4.1.0-HOP-all.jar
3f01b57e7e25f038ff9b59006dc9fe1dc9e2105cd05ac6c6b617771a9d8179c9  rskj-core-4.1.0-HOP-sources.jar
65f3b183d72166e3cce209e6546b687e9b10b9c9e0750e4a4a7f1bb28f957fed  rskj-core-4.1.0-HOP.jar
a7df6994466abffeac61405984be4237f937dd25ce0fd1c42fed1c387b2835de  rskj-core-4.1.0-HOP.module
7fdd10c4ef368fd5997f381454086645f22349c98eba9bc12b445f402839e705  rskj-core-4.1.0-HOP.pom
```

### CODE REVIEW

**Comment by nagarev** [comment]
d5ec4c766b184d13dde8c4cdef6f30481731b72c562c087bfd0c223d5709a2e6  rskj-core-4.1.0-HOP-all.jar
3f01b57e7e25f038ff9b59006dc9fe1dc9e2105cd05ac6c6b617771a9d8179c9  rskj-core-4.1.0-HOP-sources.jar
65f3b183d72166e3cce209e6546b687e9b10b9c9e0750e4a4a7f1bb28f957fed  rskj-core-4.1.0-HOP.jar
a7df6994466abffeac61405984be4237f937dd25ce0fd1c42fed1c387b2835de  rskj-core-4.1.0-HOP.module
7fdd10c4ef368fd5997f381454086645f22349c98eba9bc12b445f402839e705  rskj-core-4.1.0-HOP.pom

**Comment by nagarev** [comment]
```
d5ec4c766b184d13dde8c4cdef6f30481731b72c562c087bfd0c223d5709a2e6  rskj-core-4.1.0-HOP-all.jar
3f01b57e7e25f038ff9b59006dc9fe1dc9e2105cd05ac6c6b617771a9d8179c9  rskj-core-4.1.0-HOP-sources.jar
65f3b183d72166e3cce209e6546b687e9b10b9c9e0750e4a4a7f1bb28f957fed  rskj-core-4.1.0-HOP.jar
a7df6994466abffeac61405984be4237f937dd25ce0fd1c42fed1c387b2835de  rskj-core-4.1.0-HOP.module
7fdd10c4ef368fd5997f381454086645f22349c98eba9bc12b445f402839e705  rskj-core-4.1.0-HOP.pom
```

**Review by nagarev — APPROVED** [review]
```
d5ec4c766b184d13dde8c4cdef6f30481731b72c562c087bfd0c223d5709a2e6  rskj-core-4.1.0-HOP-all.jar
3f01b57e7e25f038ff9b59006dc9fe1dc9e2105cd05ac6c6b617771a9d8179c9  rskj-core-4.1.0-HOP-sources.jar
65f3b183d72166e3cce209e6546b687e9b10b9c9e0750e4a4a7f1bb28f957fed  rskj-core-4.1.0-HOP.jar
a7df6994466abffeac61405984be4237f937dd25ce0fd1c42fed1c387b2835de  rskj-core-4.1.0-HOP.module
7fdd10c4ef368fd5997f381454086645f22349c98eba9bc12b445f402839e705  rskj-core-4.1.0-HOP.pom
```

**Review by marcos-iov — APPROVED** [review]
Verified  
```
d5ec4c766b184d13dde8c4cdef6f30481731b72c562c087bfd0c223d5709a2e6  rskj-core-4.1.0-HOP-all.jar
3f01b57e7e25f038ff9b59006dc9fe1dc9e2105cd05ac6c6b617771a9d8179c9  rskj-core-4.1.0-HOP-sources.jar
65f3b183d72166e3cce209e6546b687e9b10b9c9e0750e4a4a7f1bb28f957fed  rskj-core-4.1.0-HOP.jar
a7df6994466abffeac61405984be4237f937dd25ce0fd1c42fed1c387b2835de  rskj-core-4.1.0-HOP.module
7fdd10c4ef368fd5997f381454086645f22349c98eba9bc12b445f402839e705  rskj-core-4.1.0-HOP.pom
```

**Pull request merged**
