### PR TITLE
Add reproducible for powpeg-node 6.2.0.0

### PR DESCRIPTION
**Pull request by marcos-iov**

### CODE REVIEW

**Comment by jeremy-then** [comment]
d472afdf7b2a3ac68879c02b151d5e10896dbf5cb9b6b2815c637a9f9f76430c  federate-node-ARROWHEAD-6.2.0.0-all.jar
26790bc374c0c5306d747885e09a6f1db01e202b799cb0fcf41e70cd832fcc36  federate-node-ARROWHEAD-6.2.0.0-sources.jar
a43309b36a32335a357a371a05e1a0da44badd5b77334bd647350795b15b3e0c  federate-node-ARROWHEAD-6.2.0.0.jar

**Review by jeremy-then — APPROVED** [review]
LGTM.

**Review by wilmerrootstock — APPROVED** [review]
LGTM!

**Review by nathanieliov — APPROVED** [review]
> docker run --rm powpeg-node/arrowhead-6.2.0.0 bash -c 'sha256sum * | grep -v javadoc.jar'
d472afdf7b2a3ac68879c02b151d5e10896dbf5cb9b6b2815c637a9f9f76430c  federate-node-ARROWHEAD-6.2.0.0-all.jar
26790bc374c0c5306d747885e09a6f1db01e202b799cb0fcf41e70cd832fcc36  federate-node-ARROWHEAD-6.2.0.0-sources.jar
a43309b36a32335a357a371a05e1a0da44badd5b77334bd647350795b15b3e0c  federate-node-ARROWHEAD-6.2.0.0.jar

**Pull request merged**
