### PR TITLE
Added reproducible for rskj/hop-4.4.0

### PR DESCRIPTION
**Pull request by kelvinator07**

### CODE REVIEW

**Comment by jeremy-then** [comment]
c89f53f64379ec2a6612ff69f94d06a0b06e1b366a9795883f2dd3d1b32387d2  rskj-core-4.4.0-HOP-all.jar
a07bcbbf2d0d7c97d50e0a8d56d483ad10033205d4517d917901a5cd2d6d4ae0  rskj-core-4.4.0-HOP-sources.jar
b04009ccfdeeaea8283039ad576954a42f621fe450752baea54a72f0e5595fe2  rskj-core-4.4.0-HOP.jar
cf5ebcf31779384f6e3afc886a16cbee1bfe07cdbf733bbfc88df7ba34b19859  rskj-core-4.4.0-HOP.module
10fb26a9ba527996c3f5af30fcd02b0f59fac02d54a10b868f8223c28c63f042  rskj-core-4.4.0-HOP.pom

**Review by jeremy-then — APPROVED** [review]
LGTM.

**Review by Vovchyk — APPROVED** [review]
```
c89f53f64379ec2a6612ff69f94d06a0b06e1b366a9795883f2dd3d1b32387d2  rskj-core-4.4.0-HOP-all.jar
a07bcbbf2d0d7c97d50e0a8d56d483ad10033205d4517d917901a5cd2d6d4ae0  rskj-core-4.4.0-HOP-sources.jar
b04009ccfdeeaea8283039ad576954a42f621fe450752baea54a72f0e5595fe2  rskj-core-4.4.0-HOP.jar
cf5ebcf31779384f6e3afc886a16cbee1bfe07cdbf733bbfc88df7ba34b19859  rskj-core-4.4.0-HOP.module
10fb26a9ba527996c3f5af30fcd02b0f59fac02d54a10b868f8223c28c63f042  rskj-core-4.4.0-HOP.pom
```

**Review by Vovchyk — CHANGES_REQUESTED** [review]
the checksums need to be updated when a new git tag is created

**Review by Vovchyk — APPROVED** [review]
```
10e82f9e4fc80487f0e0799c4082275c2360e243d12fd791cb5108a05a71f7f8  rskj-core-4.4.0-HOP-all.jar
3f4e23b9d4172572a0225b8e32f267296770832efd4acde56af7ca14c94466b1  rskj-core-4.4.0-HOP-sources.jar
4a6ac146fb03d60b9e7f0ab17302db4e821b1da8c4cc11822b9e0d33cbce2518  rskj-core-4.4.0-HOP.jar
ae3933d57088cfc9a8d6a9740309e757dcbdfeef8c9e1a0635e1f4d97f329f16  rskj-core-4.4.0-HOP.module
10fb26a9ba527996c3f5af30fcd02b0f59fac02d54a10b868f8223c28c63f042  rskj-core-4.4.0-HOP.pom
```

lgtm

**Pull request merged**
